FROM php:7.4-cli

RUN \
# For PHP core {
apt-get update && \
apt-get install -y \
    git \
# For PHP amqp-extension {
    librabbitmq-dev \
# For PHP amqp-extension }
# For PHP php-amqplib {
    libgmp-dev \
    libsodium-dev \
    libmcrypt-dev \
# For PHP php-amqplib }
    libzip-dev && \
docker-php-ext-install \
# For PHP amqp-extension {
    bcmath \
# For PHP amqp-extension }
# For PHP php-amqplib {
    sockets \
    sodium \
    gmp \
# For PHP php-amqplib }
    zip && \
pecl install amqp redis && \
docker-php-ext-enable amqp redis && \
# For PHP core }
curl -sS https://getcomposer.org/installer | php -- --filename=composer --install-dir=/usr/local/bin && \
composer self-update 1.10.20 && \
rm -rf \
    /usr/local/etc/php/php.ini-development \
    /usr/local/etc/php/php.ini-production \
    /var/lib/apt/lists/* \
    /tmp/pear

COPY ./conf/php.ini /usr/local/etc/php/php.ini